version: '3'

services:
  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./src/api:/src/api
      - ./docker/php-fpm/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./src/api:/src/api
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443

  database:
    build:
      context: docker/database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379
